apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /dev/stdout notice;
    pid        /tmp/nginx.pid;

    events {
        worker_connections  1024;
    }

    stream {
        server {
            listen 8080 proxy_protocol;
            return "HTTP/1.1 200 OK\nContent-Type: text/plain\nConnection: close\n\nReceived PROXY protocol string: $proxy_protocol_addr:$proxy_protocol_port to $proxy_protocol_server_addr:$proxy_protocol_server_port\r\n";
        }
    }
