apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: https
    - port: 8443
      protocol: UDP
      targetPort: 8443
      name: http-3
  selector:
    app: nginx
  type: ClusterIP
