apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /dev/stdout notice;
    pid        /tmp/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      proxy_temp_path /tmp/proxy_temp;
      client_body_temp_path /tmp/client_temp;
      fastcgi_temp_path /tmp/fastcgi_temp;
      uwsgi_temp_path /tmp/uwsgi_temp;
      scgi_temp_path /tmp/scgi_temp;

      map $jwt_claim_scope $valid_scope {
        "access_as_admin" 1;
      }

      server {
        listen 8080;

        location / {
          auth_jwt          "API";
          auth_jwt_require  $valid_scope;
          proxy_pass        http://httpbin.org;
        }
      }
    }
