apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    map $ssl_client_s_dn $ssl_client_s_dn_cn {
      default "";
      ~,CN=(?<CN>[^,]+) $CN;
    }

    log_format compression '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status $body_bytes_sent '
                           '"$http_referer" "$http_user_agent" "$gzip_ratio"';

    server {
      listen 8443 ssl;

      ssl_certificate /etc/nginx/certs/server.crt;
      ssl_certificate_key /etc/nginx/certs/server.key;
      ssl_client_certificate /etc/nginx/certs/rootca.pem;
      ssl_verify_client on;

      location / {
        proxy_pass https://httpbin.org;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Client-PEM $ssl_client_escaped_cert;
        proxy_set_header Client-DN $ssl_client_s_dn;
        proxy_set_header Client-CN $ssl_client_s_dn_cn;
      }
    }
